/**
 * Barcode API 服务
 * Generated by DDF Engine
 */

import request from '@/utils/request'

/**
 * 分页列表
 */
export function getBarcodeList(params) {
  return request({
    url: '/api/barcode',
    method: 'get',
    params,
  })
}

/**
 * 详情
 */
export function getBarcode(id) {
  return request({
    url: `/api/barcode/${id}`,
    method: 'get',
  })
}

/**
 * 创建
 */
export function createBarcode(data) {
  return request({
    url: '/api/barcode',
    method: 'post',
    data,
  })
}

/**
 * 更新
 */
export function updateBarcode(id, data) {
  return request({
    url: `/api/barcode/${id}`,
    method: 'put',
    data,
  })
}

/**
 * 删除
 */
export function deleteBarcode(id) {
  return request({
    url: `/api/barcode/${id}`,
    method: 'delete',
  })
}
