/**
 * BOMItem API 服务
 * Generated by DDF Engine
 */

import request from '@/utils/request'

/**
 * 分页列表
 */
export function getBOMItemList(params) {
  return request({
    url: '/api/bom-item',
    method: 'get',
    params,
  })
}

/**
 * 详情
 */
export function getBOMItem(id) {
  return request({
    url: `/api/bom-item/${id}`,
    method: 'get',
  })
}

/**
 * 创建
 */
export function createBOMItem(data) {
  return request({
    url: '/api/bom-item',
    method: 'post',
    data,
  })
}

/**
 * 更新
 */
export function updateBOMItem(id, data) {
  return request({
    url: `/api/bom-item/${id}`,
    method: 'put',
    data,
  })
}

/**
 * 删除
 */
export function deleteBOMItem(id) {
  return request({
    url: `/api/bom-item/${id}`,
    method: 'delete',
  })
}
