/**
 * Container API 服务
 * Generated by DDF Engine
 */

import request from '@/utils/request'

/**
 * 分页列表
 */
export function getContainerList(params) {
  return request({
    url: '/api/container',
    method: 'get',
    params,
  })
}

/**
 * 详情
 */
export function getContainer(id) {
  return request({
    url: `/api/container/${id}`,
    method: 'get',
  })
}

/**
 * 创建
 */
export function createContainer(data) {
  return request({
    url: '/api/container',
    method: 'post',
    data,
  })
}

/**
 * 更新
 */
export function updateContainer(id, data) {
  return request({
    url: `/api/container/${id}`,
    method: 'put',
    data,
  })
}

/**
 * 删除
 */
export function deleteContainer(id) {
  return request({
    url: `/api/container/${id}`,
    method: 'delete',
  })
}
