/**
 * Defect API 服务
 * Generated by DDF Engine
 */

import request from '@/utils/request'

/**
 * 分页列表
 */
export function getDefectList(params) {
  return request({
    url: '/api/defect',
    method: 'get',
    params,
  })
}

/**
 * 详情
 */
export function getDefect(id) {
  return request({
    url: `/api/defect/${id}`,
    method: 'get',
  })
}

/**
 * 创建
 */
export function createDefect(data) {
  return request({
    url: '/api/defect',
    method: 'post',
    data,
  })
}

/**
 * 更新
 */
export function updateDefect(id, data) {
  return request({
    url: `/api/defect/${id}`,
    method: 'put',
    data,
  })
}

/**
 * 删除
 */
export function deleteDefect(id) {
  return request({
    url: `/api/defect/${id}`,
    method: 'delete',
  })
}
