/**
 * Material API 服务
 * Generated by DDF Engine
 */

import request from '@/utils/request'

/**
 * 分页列表
 */
export function getMaterialList(params) {
  return request({
    url: '/api/material',
    method: 'get',
    params,
  })
}

/**
 * 详情
 */
export function getMaterial(id) {
  return request({
    url: `/api/material/${id}`,
    method: 'get',
  })
}

/**
 * 创建
 */
export function createMaterial(data) {
  return request({
    url: '/api/material',
    method: 'post',
    data,
  })
}

/**
 * 更新
 */
export function updateMaterial(id, data) {
  return request({
    url: `/api/material/${id}`,
    method: 'put',
    data,
  })
}

/**
 * 删除
 */
export function deleteMaterial(id) {
  return request({
    url: `/api/material/${id}`,
    method: 'delete',
  })
}
