/**
 * ProcessRoute API 服务
 * Generated by DDF Engine
 */

import request from '@/utils/request'

/**
 * 分页列表
 */
export function getProcessRouteList(params) {
  return request({
    url: '/api/process-route',
    method: 'get',
    params,
  })
}

/**
 * 详情
 */
export function getProcessRoute(id) {
  return request({
    url: `/api/process-route/${id}`,
    method: 'get',
  })
}

/**
 * 创建
 */
export function createProcessRoute(data) {
  return request({
    url: '/api/process-route',
    method: 'post',
    data,
  })
}

/**
 * 更新
 */
export function updateProcessRoute(id, data) {
  return request({
    url: `/api/process-route/${id}`,
    method: 'put',
    data,
  })
}

/**
 * 删除
 */
export function deleteProcessRoute(id) {
  return request({
    url: `/api/process-route/${id}`,
    method: 'delete',
  })
}
