/**
 * ProcessStep API 服务
 * Generated by DDF Engine
 */

import request from '@/utils/request'

/**
 * 分页列表
 */
export function getProcessStepList(params) {
  return request({
    url: '/api/process-step',
    method: 'get',
    params,
  })
}

/**
 * 详情
 */
export function getProcessStep(id) {
  return request({
    url: `/api/process-step/${id}`,
    method: 'get',
  })
}

/**
 * 创建
 */
export function createProcessStep(data) {
  return request({
    url: '/api/process-step',
    method: 'post',
    data,
  })
}

/**
 * 更新
 */
export function updateProcessStep(id, data) {
  return request({
    url: `/api/process-step/${id}`,
    method: 'put',
    data,
  })
}

/**
 * 删除
 */
export function deleteProcessStep(id) {
  return request({
    url: `/api/process-step/${id}`,
    method: 'delete',
  })
}
