/**
 * ProcessParam API 服务
 * Generated by DDF Engine
 */

import request from '@/utils/request'

/**
 * 分页列表
 */
export function getProcessParamList(params) {
  return request({
    url: '/api/process-param',
    method: 'get',
    params,
  })
}

/**
 * 详情
 */
export function getProcessParam(id) {
  return request({
    url: `/api/process-param/${id}`,
    method: 'get',
  })
}

/**
 * 创建
 */
export function createProcessParam(data) {
  return request({
    url: '/api/process-param',
    method: 'post',
    data,
  })
}

/**
 * 更新
 */
export function updateProcessParam(id, data) {
  return request({
    url: `/api/process-param/${id}`,
    method: 'put',
    data,
  })
}

/**
 * 删除
 */
export function deleteProcessParam(id) {
  return request({
    url: `/api/process-param/${id}`,
    method: 'delete',
  })
}
