/**
 * ProductBOM API 服务
 * Generated by DDF Engine
 */

import request from '@/utils/request'

/**
 * 分页列表
 */
export function getProductBOMList(params) {
  return request({
    url: '/api/product-bom',
    method: 'get',
    params,
  })
}

/**
 * 详情
 */
export function getProductBOM(id) {
  return request({
    url: `/api/product-bom/${id}`,
    method: 'get',
  })
}

/**
 * 创建
 */
export function createProductBOM(data) {
  return request({
    url: '/api/product-bom',
    method: 'post',
    data,
  })
}

/**
 * 更新
 */
export function updateProductBOM(id, data) {
  return request({
    url: `/api/product-bom/${id}`,
    method: 'put',
    data,
  })
}

/**
 * 删除
 */
export function deleteProductBOM(id) {
  return request({
    url: `/api/product-bom/${id}`,
    method: 'delete',
  })
}
