/**
 * ShiftPattern API 服务
 * Generated by DDF Engine
 */

import request from '@/utils/request'

/**
 * 分页列表
 */
export function getShiftPatternList(params) {
  return request({
    url: '/api/shift-pattern',
    method: 'get',
    params,
  })
}

/**
 * 详情
 */
export function getShiftPattern(id) {
  return request({
    url: `/api/shift-pattern/${id}`,
    method: 'get',
  })
}

/**
 * 创建
 */
export function createShiftPattern(data) {
  return request({
    url: '/api/shift-pattern',
    method: 'post',
    data,
  })
}

/**
 * 更新
 */
export function updateShiftPattern(id, data) {
  return request({
    url: `/api/shift-pattern/${id}`,
    method: 'put',
    data,
  })
}

/**
 * 删除
 */
export function deleteShiftPattern(id) {
  return request({
    url: `/api/shift-pattern/${id}`,
    method: 'delete',
  })
}
