/**
 * Skill API 服务
 * Generated by DDF Engine
 */

import request from '@/utils/request'

/**
 * 分页列表
 */
export function getSkillList(params) {
  return request({
    url: '/api/skill',
    method: 'get',
    params,
  })
}

/**
 * 详情
 */
export function getSkill(id) {
  return request({
    url: `/api/skill/${id}`,
    method: 'get',
  })
}

/**
 * 创建
 */
export function createSkill(data) {
  return request({
    url: '/api/skill',
    method: 'post',
    data,
  })
}

/**
 * 更新
 */
export function updateSkill(id, data) {
  return request({
    url: `/api/skill/${id}`,
    method: 'put',
    data,
  })
}

/**
 * 删除
 */
export function deleteSkill(id) {
  return request({
    url: `/api/skill/${id}`,
    method: 'delete',
  })
}
