/**
 * WOBOMItem API 服务
 * Generated by DDF Engine
 */

import request from '@/utils/request'

/**
 * 分页列表
 */
export function getWOBOMItemList(params) {
  return request({
    url: '/api/wobom-item',
    method: 'get',
    params,
  })
}

/**
 * 详情
 */
export function getWOBOMItem(id) {
  return request({
    url: `/api/wobom-item/${id}`,
    method: 'get',
  })
}

/**
 * 创建
 */
export function createWOBOMItem(data) {
  return request({
    url: '/api/wobom-item',
    method: 'post',
    data,
  })
}

/**
 * 更新
 */
export function updateWOBOMItem(id, data) {
  return request({
    url: `/api/wobom-item/${id}`,
    method: 'put',
    data,
  })
}

/**
 * 删除
 */
export function deleteWOBOMItem(id) {
  return request({
    url: `/api/wobom-item/${id}`,
    method: 'delete',
  })
}
