/**
 * Workshop API 服务
 * Generated by DDF Engine
 */

import request from '@/utils/request'

/**
 * 分页列表
 */
export function getWorkshopList(params) {
  return request({
    url: '/api/workshop',
    method: 'get',
    params,
  })
}

/**
 * 详情
 */
export function getWorkshop(id) {
  return request({
    url: `/api/workshop/${id}`,
    method: 'get',
  })
}

/**
 * 创建
 */
export function createWorkshop(data) {
  return request({
    url: '/api/workshop',
    method: 'post',
    data,
  })
}

/**
 * 更新
 */
export function updateWorkshop(id, data) {
  return request({
    url: `/api/workshop/${id}`,
    method: 'put',
    data,
  })
}

/**
 * 删除
 */
export function deleteWorkshop(id) {
  return request({
    url: `/api/workshop/${id}`,
    method: 'delete',
  })
}
