/**
 * WorkOrder API 服务
 * Generated by DDF Engine
 */

import request from '@/utils/request'

/**
 * 分页列表
 */
export function getWorkOrderList(params) {
  return request({
    url: '/api/work-order',
    method: 'get',
    params,
  })
}

/**
 * 详情
 */
export function getWorkOrder(id) {
  return request({
    url: `/api/work-order/${id}`,
    method: 'get',
  })
}

/**
 * 创建
 */
export function createWorkOrder(data) {
  return request({
    url: '/api/work-order',
    method: 'post',
    data,
  })
}

/**
 * 更新
 */
export function updateWorkOrder(id, data) {
  return request({
    url: `/api/work-order/${id}`,
    method: 'put',
    data,
  })
}

/**
 * 删除
 */
export function deleteWorkOrder(id) {
  return request({
    url: `/api/work-order/${id}`,
    method: 'delete',
  })
}
