/**
 * 合并 generated/backend/prisma/ 下的独立 Prisma Schema 为一个文件
 * 输出到 server/prisma/schema.prisma
 */

const fs = require('fs')
const path = require('path')

const SCHEMAS_DIR = path.resolve(__dirname, '../../generated/backend/prisma')
const OUTPUT = path.resolve(__dirname, '../prisma/schema.prisma')

const header = `// ============================================================
// DDF — Combined Prisma Schema
// Generated by combine-prisma.js
// ============================================================

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

`

if (!fs.existsSync(SCHEMAS_DIR)) {
  console.error(`❌ Schemas directory not found: ${SCHEMAS_DIR}`)
  console.error('   Run the generator first: node engine/generator/index.js')
  process.exit(1)
}

const files = fs.readdirSync(SCHEMAS_DIR).filter(f => f.endsWith('.prisma'))
let body = ''

for (const file of files) {
  const content = fs.readFileSync(path.join(SCHEMAS_DIR, file), 'utf-8')
  // Strip headers and normalize indentation
  const lines = content.split('\n')
    .filter(line => {
      const trimmed = line.trim()
      return !trimmed.startsWith('// =========') &&
             !trimmed.startsWith('generator ') &&
             !trimmed.startsWith('datasource ') &&
             !trimmed.startsWith('// Domain:')
    })
    .map(line => line.replace(/^ {2,}/, '  ')) // normalize to 2-space indent
  body += lines.join('\n') + '\n\n'
}

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true })
fs.writeFileSync(OUTPUT, header + body)

// Count models
const modelCount = (body.match(/^model /gm) || []).length
console.log(`✅ Combined ${files.length} schema files → ${OUTPUT}`)
console.log(`   Models: ${modelCount}`)
